# $schema: http://json.schemastore.org/github-workflow.json
name: pull-request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  verify-github-workflows:
    uses: harmelodic/workflows/.github/workflows/verify-github-workflows.yaml@9c9425790780e8e5a34289a409f080f2b413affd

  verify-python-project:
    uses: harmelodic/workflows/.github/workflows/verify-python-project.yaml@9c9425790780e8e5a34289a409f080f2b413affd
    with:
      target: generate_network_graph.py

  run-and-check-graph:
    permissions:
      contents: 'read'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
      - run: pip install -r requirements.txt
      - run: python generate_network_graph.py
      - run: test -f graph.html # Checks file exists and is a regular file
